### ISSUE TITLE
Optimized Prompt is an empty list with Mistral.

### ISSUE THREAD

**Issue by salokr** [XinyuanWangCS/PromptAgent#16]
Hi,

Thank you for open-sourcing your code.

I was trying to run your code using Mistral and initially, there was an error that 
```
ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as pad_token (tokenizer.pad_token = tokenizer.eos_token e.g.) or add a new pad token via tokenizer.add_special_tokens({'pad_token': '[PAD]'}).
```
To fix this, as suggested, I added the lines in the file `hf_textgeneration_model.py` (line 17):
```
if self.tokenizer.pad_token is None:
            self.tokenizer.pad_token = self.tokenizer.eos_token
```
and the issue was fixed.
Then, I ran `python src/main.py --config_dir example_config.yaml` with default settings and I found through the logs that the `optimized_prompt` is always `[]`. Am I missing something or is this an expected behaviour?

Here's my example_config.yaml file:
```
# basic settings
task_name: bigbench # bigbench | ncbi | ... | or your own task
search_algo: mcts # mcts | beam_search
print_log: true
log_dir: ./logs/

# your initial prompt
init_prompt: |
  Answer questions about a table of penguins and their attributes.

task_setting:
  train_size: 70 
  eval_size: 50 # data split for reward calculation
  test_size: 79 # if test_size is not 0, the optimized nodes will be tested at last.
  seed: 42 # if need to fixed shuffled dataset
  data_dir: ./datasets/penguins_in_a_table.json # if data is downloaded
  # Note: the current supported bigbench tasks are specified by 
  # data_dir using the same task_name (bigbench), if there is not
  # specific .py class inplemented in the tasks folder.
  post_instruction: false # false: prompt + task question | true: task question + prompt

base_model_setting:
  model_type: hf_textgeneration # openai | palm | hf_text2text | hf_textgeneration | ct_model
  model_name: mistralai/Mistral-7B-Instruct-v0.2 # api-based model'name or huggingface model name
  temperature: 0.0
  api_key: null # if need api key
  device: cuda # cuda | cpu | cuda:x, e.g. 0,1,2...
  model_path: null # ct model requires the downloaded model's path

optim_model_setting:
  model_type: hf_textgeneration # openai | palm | hf_text2text | hf_textgeneration | ct_model
  model_name: mistralai/Mistral-7B-Instruct-v0.2 # api-based model'name or huggingface model name
  temperature: 1.0
  api_key: null  # if need api key
  device: cuda # cuda | cpu | cuda:x, e.g. 0,1,2...
  model_path: null # ct model requires the downloaded model's path

search_setting:
  iteration_num: 10
  expand_width: 3 # num of branches of each node
  depth_limit: 5 # the max depth of mcts
  # mcts setting
  min_depth: 2 # min depth of mcts for early stop
  w_exp: 2.5 # balance exploration and exploitation
  # beam search setting
  beam_width: 3

world_model_setting:
  # mcts world model setting
  train_shuffle: true
  num_new_prompts: 1 # 3 if beam search
  train_batch_size: 5
 
```

I have also attached the log file for your reference. 

[20240905_191915-bigbench_penguins_in_a_table-algo_mcts-train-000.log](https://github.com/user-attachments/files/16902355/20240905_191915-bigbench_penguins_in_a_table-algo_mcts-train-000.log)

**Comment by XinyuanWangCS** [comment]
Thank you for pointing out and solve the bug! I have checked your log file. It seems the error_feedback and optimized prompt are all empty. I think there could be two reasons. 
1. HFTextGenerationModel code is incorrect. Maybe you can test HFTextGenerationModel generate function using a simple question to see if there is any output. If there is output, then the code is fine. Sorry that I don't have GPU resource, so I am unable to test it for you.
2. Optimizer is too weak. As said in the paper, the optimizer should be a strong model as teacher model that can distill the task knowledge into a prompt. The weakest optimizer we used is gpt-3.5/Palm2. Since there is a long context and complex instruction in the prompt, it could be that mistral-7b is unable to understand the optimize prompt, so it generates nothing. I would recommand using gpt-4o-mini as the optimizer.
