### ISSUE TITLE
how to use local LLMs

### ISSUE THREAD

**Issue by jzyxn** [XinyuanWangCS/PromptAgent#5]
May I ask how to deploy a local model instead of gpt?

**Comment by XinyuanWangCS** [comment]
Hi! I have implemented huggingface model version in the dev branch. You may download the dev branch code. In the Readme, you can see the "Huggingface TextGeneration Model" command to run PromptAgent. You can check the code in src/prompt_optim_agent/language_model. There is hf_text2text_model.py and hf_textgeneration_model.py. If you want to implement your own model, you can write a .py file with similar structure - load model and write a batch_forward_func/generate fucntion, and add the model type to the __init__.py.  I wrote the huggingface version but have not tried yet, due to limited GPU resource. I only tested ctranslate mistral-7b-instruct model (more gpu friendly). You can also see the command in the Readme "CTranslate model". Note: You'd better use instruction-tuned models, e.g. mistral-7b-instruct, llama-chat.

**Comment by jzyxn** [comment]
Thanks for your reply.
